name: aprendendo-github-actions
run-name: ${{ github.actor }} está aprendendo GitHub Actions
on: [push]
jobs:
  check-eslint-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g eslint
      - run: eslint -v
